[package]
name = "userman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_userman = { path = "../auth_userman" }
clap = { version = "4", features = ["derive"] }
colored = "2.0.0"
